name       : gmic
version    : 2.9.6
release    : 44
source     :
    - https://gmic.eu/files/source/gmic_2.9.6.tar.gz : d22fe8515af16dcd050d09a0bc7127ec29f4795ce732a0c6c3eaf839356bc11a
homepage   : https://gmic.eu/
license    :
    - CECILL-2.1
    - CECILL-C
component  :
    - multimedia.graphics
    - gimp : multimedia.graphics
summary    :
    - GREYC's Magic for Image Computing
    - gimp : G'MIC plugin for GIMP
description: |
    G'MIC is a full-featured open-source framework for image processing, distributed under the CeCILL free software licenses (LGPL-like and/or GPL-compatible). It provides several different user interfaces to convert / manipulate / filter / visualize generic image datasets, ranging from 1d scalar signals to 3d+t sequences of multi-spectral volumetric images, hence including 2d color images.
patterns   :
    - gimp : /usr/lib64/gimp
builddeps  :
    - pkgconfig(GraphicsMagick)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(eigen3)
    - pkgconfig(fftw3)
    - pkgconfig(gimp-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(opencv4)
    - pkgconfig(xext)
    - hdf5-devel
rundeps    :
    - gimp : gmic
setup      : |
    # Workaround : Parse error at "std"
    rm zart/.qmake.stash
build      : |
    # Build gmic
    %cmake -B build -DENABLE_DYNAMIC_LINKING=ON \
        -DBUILD_LIB_STATIC=OFF
    %make -C build -j1

    # Symlink so zart can be build with dynamic linking
    ln -s ../build/libgmic.so src/libgmic.so

    # Build gmic-qt gimp and krita plugins
    pushd gmic-qt
    export LDFLAGS="$LDFLAGS -L../build"
    %cmake -B build-qt -DENABLE_DYNAMIC_LINKING=ON \
        -DGMIC_PATH=$workdir/src \
        -DGMIC_LIB_PATH=$workdir/build \
        -DGMIC_QT_HOST=none
    %make -C build-qt -j1

    %cmake -B build-gimp -DENABLE_DYNAMIC_LINKING=ON \
        -DGMIC_PATH=$workdir/src \
        -DGMIC_LIB_PATH=$workdir/build \
        -DGMIC_QT_HOST=gimp
    %make -C build-gimp -j1

    %cmake -B build-krita -DENABLE_DYNAMIC_LINKING=ON \
        -DGMIC_PATH=$workdir/src \
        -DGMIC_LIB_PATH=$workdir/build \
        -DGMIC_QT_HOST=krita
    %make -C build-krita -j1
    popd

    # Build Zart
    pushd zart
    %qmake zart.pro \
        GMIC_DYNAMIC_LINKING=on \
        GMIC_PATH=$workdir/src \
        GMIC_LIB_PATH=$workdir/build
    %make
    popd
install    : |
    %make_install -C build
    %make_install -C gmic-qt/build-qt
    %make_install -C gmic-qt/build-gimp
    %make_install -C gmic-qt/build-krita
    cd zart
    %make_install INSTALL_ROOT="$installdir"
