name       : gmic
version    : 2.5.3
release    : 19
source     :
    - https://gmic.eu/files/source/gmic_2.5.3.tar.gz : be723f9efb1b295d1d019037c72217136be582a7af26d5d044a2009df0c4e6ec
license    :
    - CECILL-2.1
    - CECILL-C
component  :
    - multimedia.graphics
    - gimp : multimedia.graphics
summary    :
    - GREYC's Magic for Image Computing
    - gimp : G'MIC plugin for GIMP
description: |
    G'MIC is a full-featured open-source framework for image processing, distributed under the CeCILL free software licenses (LGPL-like and/or GPL-compatible). It provides several different user interfaces to convert / manipulate / filter / visualize generic image datasets, ranging from 1d scalar signals to 3d+t sequences of multi-spectral volumetric images, hence including 2d color images.
patterns   :
    - gimp : /usr/lib64/gimp
builddeps  :
    - pkgconfig(GraphicsMagick)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Core)
    - pkgconfig(eigen3)
    - pkgconfig(fftw3)
    - pkgconfig(gimp-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(opencv)
    - pkgconfig(xext)
    - hdf5-devel
build      : |
    %make -C src all -j1
install    : |
    %make_install -C src
